spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onedcutter
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
